//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_car.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int id { get; set; }
        public string CarName { get; set; }
        public Nullable<int> CarYear { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> BrandId { get; set; }
    }
}
